title: Abdenacer Naouri
logo:  /assets/img/main.png
description: PhD. Computer Science
show_downloads: false

url: "https://yourusername.github.io"
baseurl: "" # Leave this empty for user site (e.g., https://username.github.io)
author: Your Name
email: your.email@example.com
twitter_username: yourtwitterhandle
github_username: yourgithubusername
theme: jekyll-theme-minimal



github:
  is_project_page: false
