title: Abdenacer Naouri
logo:  /assets/img/main.png
description: PhD. Computer Science
show_downloads: false


author: Your Name
email: your.email@example.com
twitter_username: yourtwitterhandle
github_username: yourgithubusername
theme: jekyll-theme-minimal



github:
  is_project_page: false
